// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors From injector.go:

func initializeApp() (*Migrator, error) {
	fromOptions, err := NewFromOptions()
	if err != nil {
		return nil, err
	}
	fromRedisClient := NewFromRedisClient(fromOptions)
	toOptions, err := NewToOptions()
	if err != nil {
		return nil, err
	}
	toRedisClient := NewToRedisClient(toOptions)
	migrator := NewMigrator(fromRedisClient, toRedisClient)
	return migrator, nil
}
