// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from injector.go:

func initializeApp() (Migrator, error) {
	fromOptions, err := NewFromOptions()
	if err != nil {
		return nil, err
	}
	toOptions, err := NewToOptions()
	if err != nil {
		return nil, err
	}
	redisClients := NewRedisClients(fromOptions, toOptions)
	migrator := NewMigrator(redisClients)
	return migrator, nil
}
